# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${fmlrange}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${license}"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/${github}/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]] #mandatory
   # The modid of the mod
   modId="${modid}" #mandatory
   # The version number of the mod
   version="${modversion}" #mandatory
   # A display name for the mod
   displayName="${modname}" #mandatory
   # A URL for the "homepage" for this mod, displayed in the mod UI
   #displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
   # Option to change if mod requires the exact-same version on the server side (MATCH_VERSION),
   #ignore the server version even if it doesn't exist (IGNORE_SERVER_VERSION) or use any version but still requiring it on server-side (IGNORE_ALL_VERSION)
   # This information is displayed on server list with the X or the check-mark at the right of the server entry
   displayTest="MATCH_VERSION"
   # A file name (in the root of the mod JAR) containing a logo for display
   logoFile="pack.png" #optional
   # A text field displayed in the mod UI
   credits="${modcredits}" #optional
   # A text field displayed in the mod UI
   authors="${modauthors}" #optional
   # The description text for the mod (multi line!) (#mandatory)
   description='''${moddesc}'''
   # A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${modid}]] #optional
   # the modid of the dependency
   modId="forge" #mandatory
   # Does this dependency have to exist - if not, ordering below must be specified
   mandatory=true #mandatory
   # The version range of the dependency
   versionRange="${forgerange}" #mandatory
   # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
   # BEFORE - This mod is loaded BEFORE the dependency
   # AFTER - This mod is loaded AFTER the dependency
   ordering="NONE"
   # Side this dependency is applied on - BOTH, CLIENT, or SERVER
   side="BOTH"# Here's another dependency
[[dependencies.${modid}]]
   modId="minecraft"
   mandatory=true
   # This version range declares a minimum of the current minecraft version up to but not including the next major version
   versionRange="${minecraftversion}"
   ordering="NONE"
   side="BOTH"
